name: Buger Eats - Testes de Regressão Ui com Cypress

on: [push]

jobs:

  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    strategy:
      # Garante que os  testes não serão interrompidos ao encontrar um bug, e execute-os até o final.
      fail-fast: false
    steps:
      - name: Checkout
        uses: cypress-io/github-action@v4.2.1
      
      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn install
          # Variável de ambiente BASE_URL criada em settings, indicando o endereço que o runner deve acessar
          wait-on: ${{ secrets.BASE_URL }}
          wait-on-timeout: 120
          browser: chrome
          record: true
          group: 'UI - Chrome'
          spec: cypress/e2e/*
        env:
          # Variável de ambiente CYPRESS_RECORD_KEY criada em settings, para sincronizar com cypress dashboard
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
